# https://docs.github.com/en/actions

name: "Continuous Deployment - Release"

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  release:
    name: "Create Github Release"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags

      - name: "Get previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: "Get next tag"
        id: nexttag
        run: |
          PREVIOUSTAG=${{ steps.previoustag.outputs.tag }}
          echo "tag=$(($PREVIOUSTAG + 1))" >> $GITHUB_OUTPUT

      - name: "Install latest GitHub CLI"
        run: |
          VERSION=`curl  "https://api.github.com/repos/cli/cli/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c2-` 
          echo $VERSION
          curl -sSL https://github.com/cli/cli/releases/download/v${VERSION}/gh_${VERSION}_linux_amd64.tar.gz -o gh_${VERSION}_linux_amd64.tar.gz
          tar xvf gh_${VERSION}_linux_amd64.tar.gz
          sudo cp gh_${VERSION}_linux_amd64/bin/gh /usr/local/bin/
          gh version

      - name: "Create release on GitHub"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh release create ${{ steps.nexttag.outputs.tag }} --generate-notes --latest
          
